### ISSUE TITLE
`graph_class_local.check_symmetry`

### ISSUE THREAD

**Issue by bkj** [kfoynt/LocalGraphClustering#35]
Are you able to explain what the `check_symmetry` method in `graph_class_local` is doing?  It looks like it's checking to see if reciprocal edges exist for the first 200 edges in the graph -- is that right? 

If so, any reason why you're only checking the first 200 edges and not all edges? Seems like it'd be better to do check via something like:
```
set(edges) == set([(e[1], e[0]) for e in edges])
```

EDIT: Also, it looks like `graph_class_local` assumes all graphs are undirected?  Is that right?

~ Ben

**Comment by kfoynt** [comment]
Hi Ben,

That is right. The current methods work for undirected graphs. You could still try to call them using udirected graphs but I do not think you will get meaningful results. We need to generalize the methods first. 

The reason that we check the first 200 edges is just a design decision. We do not want to check all edges since that is computationally intensive. So we check the first 200 and hope to check if a graph is directed or not.

**Comment by bkj** [comment]
Ok thanks. I'm going to submit a pull request tomorrow that should speed up
some of the IO significantly.

~ Ben

**Comment by kfoynt** [comment]
Awesome! Thanks.
